# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 02:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DojoMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='DojoMemberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(help_text='Student or Instructor', max_length=20, verbose_name='Type of Member')),
            ],
        ),
        migrations.AddField(
            model_name='dojomember',
            name='position',
            field=models.ManyToManyField(to='dojoteam.DojoMemberType'),
        ),
    ]
